Add ViewBinding Example
jinsu4755/SOPT28_AdditionalExample pull request #6
Opened 2021-06-12 14:08 UTC by l2hyunwoo

## ViewBinding Sample
- Binding Fragment with abstract class
- AutoClearedValue with Delegate Pattern

## Related Issue
#5

2021-06-14 16:41 UTC, jinsu4755 requested changes
설명이 조금 더 있으면 좋을 것 같은 부분이 있어서 해당 부분 추가해주면 바로 머지할께! 땡스땡스

2021-06-14 16:41 UTC, jinsu4755 commented on 6. ViewBindingExample/app/build.gradle
> +        dataBinding true
설명에 dataBinding을 넣어야하는 부분을 추가해주면 좋을듯합니다~~

2021-06-14 16:41 UTC, jinsu4755 commented on 6. ViewBindingExample/README.md
> +        _binding = DataBindingUtil.inflate(inflater, resId, container, false)
DataBindingUtil 사용에 대한 설명이 더 있으면 좋겠음!

처음보는 사람들에겐 ViewBinding을 사용하려는데 왜 DataBinding을 사용하는지 혼란이 올 수 있다고 생각함!

또한 이러한 부분을 설명하려면 ViewBinding과 DataBinding에 대한 관계 설명도 있으면 좋을듯!

2021-06-17 15:56 UTC, l2hyunwoo commented on 6. ViewBindingExample/README.md
> +        _binding = DataBindingUtil.inflate(inflater, resId, container, false)
@jinsu4755 고쳤음!!

2021-06-22 11:25 UTC, jinsu4755 approved these changes

2021-06-22 11:25 UTC, merged